### PR TITLE
creating admin page

### PR DESCRIPTION
**Pull request by IRANKUND**
#### What does this PR do?
create admin dashboard
#### Description of Task to be completed?
create manager.html
create viewMessage.html
create viewUser.html
create create.html
#### How should this be manually tested?
crone github repository and execute home.html
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
https://trello.com/b/NJjsrfqs/mybrand-patrick
#### Screenshots (if appropriate)
dashboard
#### Questions:
N/A

### CODE REVIEW

**Comment by maximeish** [comment]
this is a Great job mn

**Comment by IRANKUND** [comment]
Man ntabirenze tu ndabona byambanye byinshi ejo ntakintu nakoze

**Comment by maximeish** [comment]
Mn njye ibyinshi ndi kubikora locally nzaba nkora push dor ubu nibw
nkirangiz ibya login na sign up

**Comment by IRANKUND** [comment]
Man dufite akazi kenshi sinziko ejo nzaba nabisoje

**Pull request merged**
